export { default as Day1 } from './Day1.js';
export { default as Day2 } from './Day2.js';
export { default as Day3 } from './Day3.js';
export { default as Day4 } from './Day4.js';
export { default as Day5 } from './Day5.js';
export { default as Day6 } from './Day6.js';
export { default as Day7 } from './Day7.js';
export { default as Day8 } from './Day8.js';
export { default as Day9 } from './Day9.js';
